name: Maestra Online
favicon: null
layout_spectrum: 0.41181721817702055
typography_spectrum: 0.05163244064897299
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8306200024671853
  lightness: 0.9518490238115191
  saturation: 0.9625196787528694
  rhythmicContrast: 0.3019333346746862
purpose: []
